/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-05-31 01:38:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.project1.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinGenForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/HTML/eclipse-workspace-UI/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/HTML/eclipse-workspace-UI/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project1/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123645892000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1558681726000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1558681730000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Raleway\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/project1/css/project.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\tbody,h1,h2,h3,h4,h5 {font-family: \"Raleway\", sans-serif;}\r\n");
      out.write("\t.w3-third img{margin-bottom: -6px; opacity: 0.8; cursor: pointer}\r\n");
      out.write("\t.w3-third img:hover{opacity: 1}\r\n");
      out.write("\tinput[type=button], input[type=submit] {\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tpadding: 4px 10px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable, th, tr, td {\r\n");
      out.write("\t\tborder: 1px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<title>일반 회원가입</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction win_upload() {\r\n");
      out.write("\t\tvar op = \"width=500, height=150, left=50, top=150\";\r\n");
      out.write("\t\topen(\"imgUploadForm.jsp\", \"\", op);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"w3-light-grey w3-content\" style=\"max-width:2400px\">\r\n");
      out.write("\t<div class=\"w3-center\" style=\"margin-top:120px;\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div style=\"text-align: left; margin-left:250px;\">일반 회원가입</div>\r\n");
      out.write("\t\t<form action=\"joinGen.do\" name=\"f\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"mclass\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.mclass }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"picture\" value=\"\">\r\n");
      out.write("\t\t\t<table style=\"width: 25%; height: 600px; margin-left: 38%; background-color: white; border-radius: 8%;\">\r\n");
      out.write("\t\t\t\t<tr><td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/default.png\" width=\"100\" height=\"120\" id=\"pic\"><br>\r\n");
      out.write("\t\t\t\t\t\t<font size=\"1\"><a href=\"javascript:win_upload()\">[사진등록]</a></font></td></tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"id\" id=\"id\" placeholder=\"ID\" style=\"width: 200px;\"> <input type=\"button\" value=\"중복확인\" id=\"idchk\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr><td colspan=\"2\"><input type=\"password\" name=\"pass\" id=\"pass\" placeholder=\"Password\" style=\"width: 280px;\"></td></tr>\r\n");
      out.write("\t\t\t<tr><td id=\"passworn\" colspan=\"2\"></td></tr>\r\n");
      out.write("\t\t\t<tr><td colspan=\"2\"><input type=\"text\" name=\"name\" placeholder=\"Name\" style=\"width: 280px;\"></td></tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><input type=\"radio\" name=\"gender\" value=\"1\" checked>남\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"2\">여</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr><td colspan=\"2\"><input type=\"text\" name=\"tel\" placeholder=\"Phone Number\" style=\"width: 280px;\"></td></tr>\r\n");
      out.write("\t\t\t<tr><td colspan=\"2\"><input type=\"text\" name=\"email\" placeholder=\"E-mail\" style=\"width: 280px;\"></td></tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"nick\" id=\"nick\" placeholder=\"Nick Name\" style=\"width: 200px;\"> <input type=\"button\" value=\"중복확인\" id=\"nickchk\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr><td colspan=\"2\">관심장르</td></tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: left; padding-left: 120px;\"><input type=\"checkbox\" name=\"genre\" value=\"로맨스\">로맨스</td>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: left\"><input type=\"checkbox\" name=\"genre\" value=\"코미디\">코미디</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: left; padding-left: 120px;\"><input type=\"checkbox\" name=\"genre\" value=\"공포\">공포</td>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: left\"><input type=\"checkbox\" name=\"genre\" value=\"드라마\">드라마</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: left; padding-left: 120px; width: 250px\"><input type=\"checkbox\" name=\"genre\" value=\"판타지\">판타지</td>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: left\"><input type=\"checkbox\" name=\"genre\" value=\"추리스릴러\">추리스릴러</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr><td colspan=\"2\"><input type=\"submit\" value=\"가입\"></td></tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"message\"></div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$(\"#idchk\").click(function() {\r\n");
      out.write("\t\t\t\tif($(\"#id\").val()==\"\") {\r\n");
      out.write("\t\t\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tvar data = \"id=\" + $(\"#id\").val();\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"overlapChk.jsp\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#message\").html(data);\r\n");
      out.write("\t\t\t\t\t\t\tif($(\"h3\").is(\".idchk\")) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#id\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"존재하는 아이디 입니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"사용가능한 아이디 입니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror : function(xhr) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"서버오류 : \" + xhr.status);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#nickchk\").click(function() {\r\n");
      out.write("\t\t\t\tif($(\"#nick\").val()==\"\") {\r\n");
      out.write("\t\t\t\t\talert(\"닉네임을 입력하세요.\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tvar data = \"nick=\" + $(\"#nick\").val();\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"overlapChk.jsp\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#message\").html(data);\r\n");
      out.write("\t\t\t\t\t\t\tif($(\"h3\").is(\".nickchk\")) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#nick\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"존재하는 닉네임 입니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"사용가능한 닉네임 입니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror : function(xhr) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"서버오류 : \" + xhr.status);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#pass\").keyup(function() {\r\n");
      out.write("\t\t\t\tif($(\"#pass\").val().length < 6) {\r\n");
      out.write("\t\t\t\t\t$(\"#passworn\").html(\"<font size='2' color='red'>비밀번호를 6자리 이상으로 입력하세요.</font>\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#passworn\").html(\"\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- Push down content on small screens --> \r\n");
      out.write("\t<div class=\"w3-hide-large\" style=\"margin-top:83px\"></div>\r\n");
      out.write("\t<div class=\"w3-black w3-center w3-bottom w3-padding-24\">Made by <a href=\"../board/main.do\" title=\"W3.CSS\" target=\"_blank\" class=\"w3-hover-opacity\">Jaeng</a></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /project1/member/joinGenForm.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /project1/member/joinGenForm.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/project1/member/joinGenForm.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
